name: dappstore
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  dartz: ^0.10.1
  json_annotation: ^4.8.0
  dio: ^5.0.3
  flutter_bloc: ^8.1.2
  freezed_annotation: ^2.2.0
  flutter_injected_web3:
    git:
      url: https://github.com/Orange-Wallet/flutter_injected_web3
      ref: f7e9605abaa472560f6fda2ec15eb729664af3e3
  flutter_inappwebview: ^5.7.1
  injectable: ^2.1.0
  dio_cache_interceptor: ^3.4.0
  get_it: ^7.2.0
  bloc: ^8.1.1
  hydrated_bloc: ^9.1.0
  flutter_downloader:
    git:
      url: https://github.com/Abhimanyu121/flutter_downloader
      ref: 05a47625b6e7c7973966bc274ed7d476567971d7
#      ref: 3aa04ec625f6c79779ee49edf24ecb483d8a2fcc
  android_path_provider: ^0.3.0
  device_info_plus: ^8.1.0
  path_provider: ^2.0.13
  permission_handler: ^10.2.0
  installed_apps: ^1.3.1
  wallet_connect_dart_v2: ^0.0.1
  url_launcher: ^6.1.10
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  android_intent_plus: ^3.1.6
  flutter_localization: ^0.1.10
  intl: ^0.17.0
  flutter_app_installer:
    git:
      url: https://github.com/Abhimanyu121/flutter-app-installer
      ref: 052cb4e0760771a4c900e10930eb42c2abbaa372
  cached_network_image: ^3.2.3
  shimmer_animation: ^2.1.0+1
  jovial_svg: 1.1.9
  flutter_rating_bar: ^4.0.1
  eth_sig_util: 0.0.7
  sentry_flutter: ^7.3.0
  readmore: ^2.1.0
  responsive_framework: ^0.2.0
  flutter_spinkit: ^5.1.0

  carousel_slider: ^4.2.1

# dependency_overrides:
  # stream_channel: ^2.1.1 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  json_serializable: ^6.6.1
  build_runner: ^2.3.3
  freezed: ^2.3.2
  injectable_generator: ^2.1.4
  hive_generator: ^2.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/icons/
  
  fonts:
    - family: GeneralSans
      fonts:
        - asset: assets/fonts/GeneralSans-Bold.ttf
          weight: 600
        - asset: assets/fonts/GeneralSans-BoldItalic.ttf
          weight: 600
        - asset: assets/fonts/GeneralSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/GeneralSans-Regular.ttf
          weight: 400
          style: normal
        - asset: assets/fonts/GeneralSans-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/GeneralSans-MediumItalic.ttf
          weight: 500
